### PR TITLE
Upgrade to Avalonia 11.0.0 preview4

### PR DESCRIPTION
**Pull request by hamster620**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaEdit?pullRequest=293) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaEdit?pullRequest=293) before we can accept your contribution.<br/><br/>:x: hamster620 [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaEdit?pullRequest=293)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/AvaloniaEdit?pullRequest=293) it.</sub>

**Comment by Gillibald** [comment]
We will most likely make `TextInputEventArgs` and `KeyEventArgs` public again for the next preview

**Comment by alexhelms** [comment]
Bumping this to bring attention so it can be merged 😄

**Comment by Gillibald** [comment]
We will release preview 5 soon that includes reverted changes to key and input event args ctor visibility.

**Comment by danipen** [comment]
Will be upgraded to preview 5 soon.

**Pull request closed without merging**
