### PR TITLE
Enable compiled bindings

### PR DESCRIPTION
**Pull request by hez2010**
Make completion list trimming compatible.

### CODE REVIEW

**Comment by danipen** [comment]
Building on top of this comment. 
https://github.com/AvaloniaUI/Avalonia/pull/10880#issuecomment-1493372348

Should we avoid enabling by default here?

**Comment by Numpsy** [comment]
I've been trying to get an app updated from Avalonia 11 preview 4 and the related lib versions to the latest versions of things, with compiled bindings and trimming enabled, and AvaloniaEdit appears to be working there (though i'm not using completions).

Are compiled bindings supposed to be disabled at the top of CompletionList.xaml ?

**Comment by hez2010** [comment]
I tested the demo app, and the CompletionList works fine.

**Comment by danipen** [comment]
cc/ @Gillibald @danwalmsley @Takoooooo @kekekeks @grokys

**Review by Gillibald — APPROVED** [review]

**Pull request merged**
