### PR TITLE
Ignore empty line copy

### PR DESCRIPTION
**Pull request by alluLinger**
if text is empty should not be copied, "\n" is not empty string so it will copied.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaEdit?pullRequest=168) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaEdit?pullRequest=168) before we can accept your contribution.<br/><br/>:x: alluLinger [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaEdit?pullRequest=168)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/AvaloniaEdit?pullRequest=168) it.</sub>

**Comment by danipen** [comment]
@alluLinger please can you describe the original issue and the failing scenario so you need to add that check?

Thanks!

**Comment by alluLinger** [comment]
@danipen 
a edit with empty text and "ctrl + c" then AvaloniaEdit will set empty to clipboard replace former one.
WPF TextBox , or others app like notepad.exe, if real nothing selected and line empty it will not replace clipboard.

**Comment by danipen** [comment]
@alluLinger thank you for the clarification. Just to fully understand your issue.

I'm assuming you're using `Options.CutCopyWholeLine`, right?

**Comment by alluLinger** [comment]
@danipen I'm not set `Options.CutCopyWholeLine` , default seem to be `True`. and yes this issue should only for cut/copy whole line.
When edit just has one line ,first line can be really empty text '', others at least contains '\n'.

**Review by danipen — APPROVED** [review]
LGTM

**Pull request merged**
