### PR TITLE
textmate: added pascal highlighting

### PR DESCRIPTION
**Pull request by AlphaNecron**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaEdit?pullRequest=198) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaEdit?pullRequest=198) before we can accept your contribution.<br/><br/>:x: AlphaNecron [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaEdit?pullRequest=198)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/AvaloniaEdit?pullRequest=198) it.</sub>

**Review by danipen — CHANGES_REQUESTED** [review]
Please add a "pascal" sample file in the Demo application using the grammar scope name **_(source.pascal)_**, so we can play with it. Thanks!

**Comment by AlphaNecron** [comment]
where can I add it?

**Comment by AlphaNecron** [comment]
The example can be whatever right?

**Review by danipen — APPROVED** [review]

**Pull request merged**
