### PR TITLE
Avalonia 0.10.7

### PR DESCRIPTION
**Pull request by BAndysc**

### CODE REVIEW

**Review by danwalmsley — APPROVED** [review]

**Comment by garyhertel** [comment]
Any idea when this might get merged? There's a fix I could really use :)

**Comment by chrisg32** [comment]
Is this merge just waiting on CI? Anything I can do to help?

**Comment by Gillibald** [comment]
@danwalmsley

**Comment by garyhertel** [comment]
Thanks Dan!

Do you know when we might see a new Nuget version for this as well?

https://www.nuget.org/packages/Avalonia.AvaloniaEdit/

**Pull request merged**
