### PR TITLE
WIP: updated code to work with new FormattedText implementation

### PR DESCRIPTION
**Pull request by adirh3**
Updated code to work with new FormattedText implementation, tests not fixed yet.
Will wait for official Avalonia release (11.0) before merging this.

### CODE REVIEW

**Comment by danipen** [comment]
This changes bring double-byte support to AvaloniaEdit, but glyph measure doesn't seem to be accurate...
double-byte

**Comment by danipen** [comment]
Hey @adirh3 @whistyun.

What os the status of this PR? Still WIP?

Could se move It to be meged while @Gillibald finishes #216?

**Comment by adirh3** [comment]
> Hey @adirh3 @whistyun.
> 
> What os the status of this PR? Still WIP?
> 
> Could se move It to be meged while @Gillibald finishes #216?

Since Avalonia master is still going through changes as @Gillibald fixes text processing issues I wanted to wait with it.
It's working, but unit tests are failing as FormattedText cannot be mocked anymore (if I remember correctly)
I think it's better to stick with @Gillibald, closing this

**Comment by danipen** [comment]
Hey @adirh3 / @whistyun. I [fixed the unit tests here](https://github.com/AvaloniaUI/AvaloniaEdit/pull/220), but long lines support is still broken due to Bidi process that makes things slower, so I'm afraid it's better to wait for #216 to be finished to get double-byte suppport.

**Pull request closed without merging**
