### PR TITLE
Linux/OSX support

### PR DESCRIPTION
**Pull request by kekekeks**
Make example csproj file compatible with *nix platforms

### CODE REVIEW

**Comment by aelij** [comment]
Skia 1.57 isn't supported on .NET Core 1.1?

**Comment by kekekeks** [comment]
No compatible binaries for Linux

**Comment by aelij** [comment]
@danwalmsley Any idea why the AppVeyor build is failing?

**Comment by danwalmsley** [comment]
Thanks @kekekeks

**Pull request merged**
