### PR TITLE
Update to Avalonia 11 preview 8

### PR DESCRIPTION
**Pull request by danipen**
Update the codebase to Avalonia 11 preview 8.

### CODE REVIEW

**Comment by danipen** [comment]
Unit test project is not compiling due to internal API visibility. We probably need to migrate these tests to the headless platform.

**Comment by danipen** [comment]
cc/ @maxkatz6 @grokys @danwalmsley @Gillibald @kekekeks

**Comment by maxkatz6** [comment]
On my way to migrate these tests https://github.com/AvaloniaUI/Avalonia/pull/11146

**Comment by maxkatz6** [comment]
@danipen done, but we probably need to wait until https://github.com/AvaloniaUI/Avalonia/pull/11169 is merged at least. It should be fine to target preview7 in the main project and nightly in the tests project. As necessary changes affect only tests.

**Comment by danipen** [comment]
@maxkatz6 should the tests green? I'm getting some errors:
```
Message
    System.InvalidOperationException : Avalonia Headless platform has failed to initialize.
Stack Trace: 
<>c__DisplayClass19_0.<StartNew>b__0() line 94
--- End of stack trace from previous location ---
HeadlessUnitTestSession.StartNew(Type entryPointType) line 111
HeadlessUnitTestSession.GetOrStartForAssembly(Assembly assembly) line 142
AvaloniaTestAttribute.Wrap(TestCommand command) line 20
SimpleWorkItem.MakeTestCommand()
SimpleWorkItem.PerformWork()
```

And also:
```
Message
    System.InvalidOperationException : Setup was already called on one of AppBuilder instances
Stack Trace: 
AppBuilder.Setup() line 287
AppBuilder.SetupWithoutStarting() line 187
<>c__DisplayClass19_0.<StartNew>b__0() line 90
--- End of stack trace from previous location ---
HeadlessUnitTestSession.StartNew(Type entryPointType) line 111
HeadlessUnitTestSession.GetOrStartForAssembly(Assembly assembly) line 142
AvaloniaTestAttribute.Wrap(TestCommand command) line 20
SimpleWorkItem.MakeTestCommand()
SimpleWorkItem.PerformWork()```

**Comment by maxkatz6** [comment]
@danipen yes, it was green locally, maybe wrong build number. I will check.

**Comment by danipen** [comment]
BTW loving this change, unit tests get much more simple!

**Comment by danipen** [comment]
> yes, it was green locally, maybe wrong build number. I will check.

@maxkatz6 did you take a look into it?

**Comment by maxkatz6** [comment]
Yes, non-UI tests in this repo are using Dispatcher, which is uses before proper headless initialization, caching incorrect dispatcher implementation. I need to figure out how to avoid it without affecting this code base too much.

**Comment by danipen** [comment]
@maxkatz6 any updates on this?

**Comment by maxkatz6** [comment]
@danipen done. Should be ready to merge as preview7 or preview8 or both.
Tests project references master branch as only that one has needed headless changes to support NUnit and more. But non-test code wasn't changed, it still preview7.

**Review by maxkatz6 — APPROVED** [review]

**Comment by Gillibald** [comment]
Let us target preview8 as that is the most recent version

**Comment by hez2010** [comment]
Hello, is there any chance of publishing a preview8 package on nuget?

**Comment by Gillibald** [comment]
https://www.nuget.org/packages/Avalonia.AvaloniaEdit/11.0.0-preview8

**Comment by hez2010** [comment]
Oops, I missed that one.
Thank you.

**Pull request merged**
