### PR TITLE
Search panel

### PR DESCRIPTION
**Pull request by aelij**
Not working yet. When adding the panel to the `AdornerLayer`, its template isn't applied for some reason. Could someone please take a look?

### CODE REVIEW

**Comment by danwalmsley** [comment]
I bet @grokys would know why straight away!
Has its style been loaded?

**Comment by danwalmsley** [comment]
By style I mean template.xaml

**Comment by danwalmsley** [comment]
I think you need to add an entry in the demo app.xaml for drop down.xaml and for searchpanel.xaml.

**Comment by aelij** [comment]
I added them all to AvaloniaEdit.xaml. From what I can tell the XAML loads (OmniXAML complains about errors).

**Comment by danwalmsley** [comment]
I should get chance to try it out tonight, will update you what I find.

**Pull request merged**
