### PR TITLE
Attempt to prevent folding crashes

### PR DESCRIPTION
**Pull request by Gillibald**
Fixes: #272

### CODE REVIEW

**Comment by HendrikMennen** [comment]
For me this fixes the issue :)

**Comment by Numpsy** [comment]
The error I was seeing seems ok with this change as well :-)

**Comment by danipen** [comment]
@HendrikMennen can you describe the issue? I disabled `AllowToScrollBelowDocument` and it seems to work fine for me:
folding

**Comment by HendrikMennen** [comment]
If I collapse something at the bottom of an element it looks like this.
image

Once I force it to redraw by resizing or scrolling the issue is resolved.

**Comment by danipen** [comment]
Could you provide a repro case in the demo application?

**Comment by HendrikMennen** [comment]
Okay nevermind it was my fault, sorry! It works perfectly now :)

**Comment by danipen** [comment]
Glad to hear that!

**Pull request merged**
